AllCops:
  TargetRubyVersion: 3.2.2
  NewCops: enable
  SuggestExtensions: false

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 150
Metrics/BlockLength:
  Max: 100
Metrics/MethodLength:
  Max: 25
Metrics/ClassLength:
  Max: 150
Metrics/AbcSize:
  Max: 40
