version: '3'
services:
  webapp:
    image: parabank
    ports:
      - "8080:8080"
      - "61616:61616"
      - "9001:9001"
  tests:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - webapp
    volumes:
      - ./reports:/usr/src/parabank/reports