version: '3'
services:
  webapp:
    image: parabank:latest
    ports:
      - "8080:8080"

  tests:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - webapp
    volumes:
      - ./reports:/usr/src/parabank/reports
