version: 2.1

jobs:
  SCAR:
    docker:
      - image: ruby:3.2.2
    steps:
      - checkout
      - run:
          name: Run RuboCop
          command: |
            bundle install
            bundle exec rubocop --format simple --fail-level E

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  say-hello-workflow:
    jobs:
      - SCAR
