version: 2.1

jobs:
  linter-check:
    docker:
      - image: ruby:3.2.2
    steps:
      - checkout
      - run:
          name: Run RuboCop
          command: |
            bundle install
            bundle exec rubocop --format simple --fail-level E

  build-app:
    docker:
      - image: parasoft/parabank:latest
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
      - image: ruby:3.2.2
    working_directory: /usr/src/parabank

    steps:
      - checkout

      # Run your tests in the second container
      - run:
          name: Run Cucumber Tests
          command: |
            docker-compose up -d webapp
            docker-compose run tests

workflows:
  version: 2
  build:
    jobs:
      - linter-check:
          filters:
            branches:
              only:
                - master
      - build-app:
          filters:
            branches:
              only:
                - master
