version: 2.1

jobs:
  linter-check:
    docker:
      - image: ruby:3.2.2
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          name: Run RuboCop
          command: |
            bundle install
            bundle exec rubocop --format simple --fail-level E

  authenticate-with-docker-hub:
    docker:
      - image: docker:20.10.17
    steps:
      - checkout
      - run:
          name: Authenticate with Docker Hub
          command:
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

  build-app:
    docker:
      - image: docker:20.10.17
    steps:
      - checkout
      - run:
          name: Pull Test App Container
          command: |
            apt-get install sudo
            sudo apt-get update
            sudo systemctl status docker
            sudo systemctl start docker
            sudo usermod -aG docker $USER
            sudo systemctl status docker
            docker-compose pull webapp

  run-tests:
    docker:
      - image: docker:20.10.17
    steps:
      - checkout
      - run:
          name: Build Container with Tests
          command: |
            docker-compose up -d webapp
      - run:
          name: Execute Tests
          command: |
            docker-compose run tests

workflows:
  version: 2
  build:
    jobs:
      - linter-check:
          filters:
            branches:
              only:
                - master
                - circleci-project-setup
      - authenticate-with-docker-hub
      - build-app:
          requires:
            - authenticate-with-docker-hub
      - run-tests:
          requires:
            - authenticate-with-docker-hub
            - build-app
